### ISSUE TITLE
How to show the trajectory of the agent?

### ISSUE THREAD

**Issue by ElizabethDuo** [danielgordon10/thor-iqa-cvpr-2018#2]
Hi Daniel, your work of showing trajectory of the agent is really great!
I also train RL agent in ai2-thor. But now the agent is invisible, so it is hard to observe it. Could you please tell me how to show the trajectory?
Thanks!

**Comment by ElizabethDuo** [comment]
I found a simple way to show agent's each step position using matplotlib. But it is not so good as showing trajectory. Hope for more tips of showing trajectory of visualizing the agent. Thanks again!

**Comment by lone17** [comment]
> I found a simple way to show agent's each step position using matplotlib. But it is not so good as showing trajectory. Hope for more tips of showing trajectory of visualizing the agent. Thanks again!

I'm trying to show the trajectory of the agent as in Daniel's example, however I cannot find any piece of code to do that in his repo. Could you please provide me with the code of your approach ? 
Much appreciation !
